workdir: .

max_threads_per_rule: 4

dcc_lab: anshul-kundaje
dcc_award: UM1HG009442
dcc_mode: prod

archr_seed: 8757647
archr_min_frags: 3000

seurat_seed: 2398756

rna_ref_counts: https://www.livercellatlas.org/data_files/toDownload/rawData_human.zip
rna_ref_metadata: https://www.livercellatlas.org/data_files/toDownload/annot_humanAll.csv

doublet_formation_rate: 0.075