workdir: .

max_threads_per_rule: 4

dcc_lab: anshul-kundaje
dcc_award: UM1HG009442
dcc_mode: prod

archr_seed: 8757647
archr_min_frags: 5000
archr_min_tss_enr: 5

seurat_seed: 2398756
seurat_min_count: 1000
seurat_max_pct_mito: 5

rna_ref_counts: https://www.livercellatlas.org/data_files/toDownload/rawData_human.zip
rna_ref_metadata: https://www.livercellatlas.org/data_files/toDownload/annot_humanAll.csv

# doublet_formation_rate: 0.15
doublet_formation_rate: 0.3